version: 2
updates:
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: Bump
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: Bump
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: Bump
